services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5001:5000
    environment:
      # https://distribution.github.io/distribution/about/configuration/
      REGISTRY_HTTP_SECRET: 8f89452d-07fd-4049-aa69-bee0f0823e01
      REGISTRY_AUTH: token
      REGISTRY_AUTH_TOKEN_REALM: http://192.168.1.12:9901/dist_auth
      REGISTRY_AUTH_TOKEN_SERVICE: Authentication
      REGISTRY_AUTH_TOKEN_ISSUER: Tumu
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /auth/ca.key
    volumes:
      - ./tmp:/auth
  # /var/lib/registry is a volume
  # /auth
  # /certs
